### Steps:
### 1. Import Libraries

In [61]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

### 2. Read dataset and define variables

In [50]:
data = pd.read_csv("Downloads/bc.csv")
X=data.drop(['Class'],axis=1)
y=data['Class']

### 3. Divide in training and testing dataset

In [51]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.15,random_state=10)

### 4. Train Support Vector Classifier model

In [52]:
model = SVC()
model.fit(X_train, y_train) 

C:\Users\Mitwa Palkhiwala\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

### 5. Prediction using the trained model 

In [53]:
predicted=model.predict(X_test)

### 6. Find the accuracy

In [54]:
print (accuracy_score(y_test, predicted))

0.9514563106796117


### 7. Print Confusion Matrix

In [59]:
confusion_matrix(y_test, predicted,labels=[1,0])

array([[30,  4],
       [ 1, 68]], dtype=int64)

### 8. List the support vectors

In [55]:
model.support_vectors_

array([[199.,   1.,   1., ...,   1.,   1.,   1.],
       [ 23.,   3.,   1., ...,   2.,   1.,   1.],
       [338.,   1.,   1., ...,   3.,   1.,   1.],
       ...,
       [265.,   7.,   9., ...,   5.,   3.,   3.],
       [335.,   8.,   6., ...,   3.,   4.,   2.],
       [274.,   7.,   2., ...,   3.,   3.,   1.]])

### 9. Indices of Support Vectors

In [56]:
model.support_

array([  1,   2,   3,   4,   6,   9,  11,  14,  15,  16,  17,  18,  19,
        24,  26,  27,  29,  30,  38,  39,  40,  43,  45,  46,  47,  49,
        50,  51,  54,  56,  57,  58,  60,  63,  66,  67,  70,  71,  73,
        74,  75,  76,  78,  79,  80,  82,  83,  84,  85,  86,  89,  90,
        91,  93,  95,  99, 101, 104, 107, 108, 109, 111, 112, 113, 115,
       117, 118, 121, 122, 123, 124, 125, 127, 128, 132, 134, 135, 136,
       137, 138, 140, 141, 142, 143, 144, 146, 151, 152, 154, 155, 156,
       157, 159, 162, 163, 165, 167, 168, 170, 171, 172, 174, 176, 177,
       178, 179, 181, 182, 183, 185, 186, 188, 189, 191, 192, 194, 195,
       196, 197, 198, 200, 202, 206, 208, 209, 213, 214, 215, 216, 221,
       222, 223, 224, 226, 228, 232, 233, 235, 236, 237, 238, 241, 246,
       247, 248, 249, 253, 254, 255, 256, 257, 258, 261, 262, 264, 265,
       267, 268, 269, 270, 271, 272, 274, 276, 277, 278, 279, 282, 284,
       285, 287, 288, 289, 291, 293, 294, 296, 297, 298, 299, 30

### 10. Number of support vectors in each class

In [57]:
model.n_support_

array([353, 205])